### ISSUE TITLE
Documentation Request: Flow Diagram showing API calls

### ISSUE THREAD

**Issue by PhillipJacobsen** [ArkEcosystem/pay#13]
It would be great if there was a flow chart showing the API calls.  It would serve as a good simple example of the preferred way to search for transactions.
I would like to create a C++ version and the API transaction flow chart would be a great help

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
