### ISSUE TITLE
React App (CRA 2.x.x) crashes in production build

### ISSUE THREAD

**Issue by Lemii** [ArkEcosystem/pay#18]
The (minified) production build of a React app made with `create-react-app` will crash when it tries to load the ARK Pay package. This does not happen in a (unminified) dev environment. 

It is most likely an incompatibility with CRA's default webpack configuration of the minifier/uglifier ([link to a similar issue](https://github.com/airbnb/react-with-styles/issues/151)). The CRA user has no control over these settings though.

**Expected Behavior**
ARK Pay should be compatible with the build settings used by `create-react-app`. 

**Current Behavior**
When the App attempts to load a component that imports the ARK Pay package, the app will crash and display the following error in the console:

`index.umd.js:909 Uncaught (in promise) TypeError: Super expression must either be null or a function`

**Steps to Reproduce (for bugs)**
1. Create a project with `npx create-react-app my-app`
2. Implement ARK Pay
3. Create a production build with `npm run build`
4. Deploy and view App

**Context**
I encountered this issue while trying to implement ARK Pay on ScanBlocks.io

**Your Environment**
- Create React App v2.1.8
- ARK Pay v0.1.12
- node v10.15.3
- npm v6.9.0
- W10

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by Lemii** [comment]
I've found a workaround in using [react-app-rewired](https://github.com/timarney/react-app-rewired), a tool that lets you manipulate parts of the webpack config of your `create-react-app` without having to eject the project.

By changing the minimizer plugin to `uglifyjs-webpack-plugin`, the error in the production build is gone.

> **config-overrides.js**  
```js 
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = function override(config, env) {
  config.optimization = {
    minimizer: [new UglifyJsPlugin()]
  };

  return config;
};
```

Of course this is not a real solution to the problem though. A user shouldn't have to do this to make ARK Pay work in their CRA v2.x.x project.

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
