### ISSUE TITLE
React App (3.x.x) refuses to invoke ArkPay class

### ISSUE THREAD

**Issue by Lemii** [ArkEcosystem/pay#19]
In the latest version of `create-react-app` (3.x.x), you get an error when you try to invoke the ArkPay class.

Importing the package ES5 or ES6 style makes no difference.

The exact same code works in CRA 2.x.x.

CRA is a popular toolset used by a lot of people. Therefore I think that it's important that ARK Pay is compliant with all of the newer major versions.

**Expected Behavior**
The ArkPay class should be invoked.

**Current Behavior**
When you try to invoke to ArkPay class you get the following error:

```
Unhandled Rejection (TypeError): Class constructor c cannot be invoked without 'new'
```

**Steps to Reproduce (for bugs)**

1. Create an app with `npx create-react-app my-app`
2. Import the ARKPay package
```
import ArkPay from '@arkecosystem/pay';
```
3. Attempt to invoke the ArkPay class
```
const gateway = new ArkPay(); 
```
4. Get the error

**Context**
I've ran into this issue by trying to troubleshoot #18 . In that issue I was using CRA 2.1.8, and wanted to see if upgrading to the latest v3.0.0+ version would help solve it. Unfortunately this new issue popped up while trying to do so.

**Your Environment**
- Create React App v3.0.1
- ARK Pay v0.1.12
- node v10.15.3
- npm v6.9.0
- W10

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
