### ISSUE TITLE
Interval does not get cleared on anything other than 'completed' status

### ISSUE THREAD

**Issue by Lemii** [ArkEcosystem/pay#20]
The intervals do not get cleared when resetting / aborting the gateway due to an erroneous   variable assignment conditional statement in the listener.

**Expected Behavior**
When calling the `.reset()` method, either directly or via `__abort()`, the interval should be cleared.

**Current Behavior**
The only time the interval gets cleared is when a payment is completed. 

**Possible Solution**
Change the variable assignment in the `__mountListener` method  (`this.started`) to the same assignment as in the `reset()` method (`this.data.started`).

**Steps to Reproduce (for bugs)**
1. Create a project with ARK Pay
2. Try to stop the gateway with `.reset()`, or force an error
3. Look at your dev tools and notice the gateway is still fetching requests every second

A PR has been created. 

**Your environment**  
- ARK Pay v0.1.12
- node v10.15.3
- npm v6.9.0
- W10

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
