### ISSUE TITLE
ARKStickers.com Dev Team feedback on ARK Pay

### ISSUE THREAD

**Issue by coolchainio** [ArkEcosystem/pay#22]
Here is some information about their experience using ARK Pay, thought I'd forward it along here for safekeeping.

- Currently the only examples and demos of ARKPay are witten for React and VueJS. It would have been really useful to have a vanilla JavaScript example to work off of, because we used ExpressJS to create the website.

- Also, the current demos appear to be clientside implementations* (Not familiar with React or Vue so could be wrong). It would have been good to have a server+client example.

- We also had an issue because the client side (browser) needs to keep contacting the server to check ARKPay if a payment is made. 
This isn't really a problem with ARKPay itself, but neither Moe or I had any experience with server polling before, so it would have been good to have an example of that or event some advice on how to handle that in the best way.

- If ARK Pay could hold multiple instances and keep track of each instance that would be very helpful and solve a lot of problems we had. Multiple instances are needed, so if two people pay at the same time ARKPay doesn't clash with itself.

- Documentation was a bit bare, it would have been useful to have documentation on timeout management, so ARKpay doesn't run 24/7 on the server, and only when needed.

All in all though, they said it was really good and a great library for accepting ARK payments. Cheers!

**Comment by ghost** [comment]
**Thanks for opening this issue!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by coolchainio** [comment]
I accidentally published this issue as my tutorials account instead of @doubled1c3

**Comment by ghost** [comment]
This issue has been closed. If you wish to re-open it please provide additional information.
